### ISSUE TITLE
fitting without constraining to LDSR/w_hm3.justrs

### ISSUE THREAD

**Issue by gnarw** [precimed/mixer#13]
I am using the mixer.py fit commands as in the readme file
but using my own summary statistics.
Fitting the model and constraining on the w_hm3.justrs seems to run fine.
When fitting the model without constraining on the w_hm3 and loading the parameters from the previous fit there is an error. Also the ...test.json files are not being made.

Here are mixer.py commands and output:

[mixer_fit_univariate_test.txt](https://github.com/precimed/mixer/files/3676019/mixer_fit_univariate_test.txt)

Any ideas what is causing this error.

**Comment by ofrei** [comment]
@gnarw This should be fixed now, could you please pull an update and re-run?
Sorry for the hassle - it's on my list to implement better unit tests and travis continuous integration (i.e. running tests automatically for each commit to mixer repository), but I haven't got time for this yet

**Comment by gnarw** [comment]
@ofrei Thanks for this.
I pulled the update and ran the commands again.
Unfortunately I now got a new error message.

[error.txt](https://github.com/precimed/mixer/files/3680256/error.txt)

**Comment by ofrei** [comment]
@gnarw this log contains warnings (true, have to fix those),  but no errors - did you check if output files are successfully created?

**Comment by gnarw** [comment]
@ofrei Sorry, I was a bit hasty. I can see now that these are only warnings.
Yes, the output files (...fit.json  and ...test.json) are are being created.
