### ISSUE TITLE
bgmglib.so file

### ISSUE THREAD

**Issue by merelpostema** [precimed/mixer#15]
I cannot find the bgmglib.so file, which is supposed to be in <MIXER_ROOT>/src/build/lib/bgmglib.so.

**Comment by ofrei** [comment]
What operating system are you using?

**Comment by merelpostema** [comment]
I am using Windows 10, but I don't see how this relates to my question, since the file seems missing on the github webpage, which should be the same for everyone regardless of operating system. As stated under the section 'data preparation > reference panel' (https://github.com/precimed/mixer/tree/master/precimed), the mixer.py scripts needs the lib file bgmglib.so as input, but I cannot find this file online.

**Comment by ofrei** [comment]
MiXeR is not yet supported on Windows. Instead you should run it on Linux.
This is related because bgmglib.so file is produced by building MiXeR
source code.

**Comment by merelpostema** [comment]
Ah ok, thanks for explaining!
