### ISSUE TITLE
Runtime_error can't call set_weights_randprune before set_ld_r2_csr

### ISSUE THREAD

**Issue by JulongWei** [precimed/mixer#16]
Hi Alex,

Before I have successfully run one Chromosome. But when I ram 22 chromosomes it reported the error. The following is log file. Could you help me figure it out? I also try to solve this problem myself.
Thank you very much!

Best,
Julong

INFO:root:__init__(lib_name=/net/mulan/home/julongw/mixer/src/build/lib/libbgmg.so, context_id=0)
INFO:root:init_log(./MyResults/UM1_MiXeR_Uni/ADD.fit.log)
INFO:root:log_message(***********************************************************************
* mixer.py: Univariate and Bivariate Causal Mixture for GWAS
* Version 1.0.0
* (c) 2018-2019 Oleksandr Frei, Alexey A. Shadrin
* Norwegian Centre for Mental Disorders Research / University of Oslo
* GNU General Public License v3
***********************************************************************
Call: 
./mixer.py fit \
	--lib /net/mulan/home/julongw/mixer/src/build/lib/libbgmg.so \
	--extract /net/mulan/home/julongw/Project1_human_imap/MyData/UM1/zzz_snplist \
	--threads 20 \
	--bim-file /net/mulan/home/julongw/Project1_human_imap/MyData/UM1/zzz_chr.@.bim \
	--ci-alpha 0.05 \
	--trait1-file /net/mulan/home/julongw/Project1_human_imap/MyData/UM1_summ/ADD.summ.gz \
	--frq-file /net/mulan/home/julongw/Project1_human_imap/MyData/UM1/zzz_chr.@.frq \
	--out ./MyResults/UM1_MiXeR_Uni/ADD.fit \
	--plink-ld-bin0 /net/mulan/home/julongw/Project1_human_imap/MyData/UM1/zzz_chr.@.p05_SNPwin50k.ld.bin 
)
INFO:root:__init__(lib_name=/net/mulan/home/julongw/mixer/src/build/lib/libbgmg.so, context_id=0)
Traceback (most recent call last):
  File "/net/mulan/home/julongw/mixer/precimed/mixer.py", line 23, in <module>
    args.func(args)
  File "/net/mulan/home/julongw/mixer/precimed/mixer/cli.py", line 605, in execute_fit_parser
    libbgmg.set_weights_randprune(args.randprune_n, args.randprune_r2)
  File "/net/mulan/home/julongw/mixer/precimed/mixer/libbgmg.py", line 122, in set_weights_randprune
    return self._check_error(self.cdll.bgmg_set_weights_randprune(self._context_id, n, r2))
  File "/net/mulan/home/julongw/mixer/precimed/mixer/libbgmg.py", line 383, in _check_error
    raise RuntimeError(self.get_last_error())
RuntimeError: runtime_error:  can't call set_weights_randprune before set_ld_r2_csr

**Comment by ofrei** [comment]
Could you please check if ``./MyResults/UM1_MiXeR_Uni/ADD.fit.log`` file exists?
