### ISSUE TITLE
'mixer_figures.py one' failed with one json file

### ISSUE THREAD

**Issue by yunhanch** [precimed/mixer#22]
I used 'mixer_figures.py one' to make plots for univariate results on SAGA. I tested 4 *test.json files, 1 failed. The run command and error message are shown below:

python /cluster/projects/nn9114k/yunhanc/github/mixer/precimed/mixer_figures.py one --json /cluster/projects/nn9114k/yunhanc/results/mixer/univariate_output/PGC_MDD_2018_no23andMe_noUKBB.test.json --out /cluster/projects/nn9114k/yunhanc/results/mixer/univariate_output/PGC_MDD_2018_no23andMe_noUKBB.test

generate /cluster/projects/nn9114k/yunhanc/results/mixer/univariate_output/PGC_MDD_2018_no23andMe_noUKBB.test.csv from 1 json files...
Done.
Traceback (most recent call last):
File "/cluster/projects/nn9114k/yunhanc/github/mixer/precimed/mixer_figures.py", line 15, in 
args.func(args)
File "/cluster/projects/nn9114k/yunhanc/github/mixer/precimed/mixer/figures.py", line 406, in execute_one_parser
make_power_plot(data_list, traits=traits_list, power_thresh=args.power_thresh)
File "/cluster/projects/nn9114k/yunhanc/github/mixer/precimed/mixer/figures.py", line 235, in make_power_plot
current_s_ci = [float(interp1d(np.log10(data_power['nvec']),data_power['svec'])(np.log10(data['options']['trait1_nval']))) for data_power in data['power_ci']]
File "/cluster/projects/nn9114k/yunhanc/github/mixer/precimed/mixer/figures.py", line 235, in 
current_s_ci = [float(interp1d(np.log10(data_power['nvec']),data_power['svec'])(np.log10(data['options']['trait1_nval']))) for data_power in data['power_ci']]
KeyError: 'nvec'

**Comment by ofrei** [comment]
@yunhanch could you pull an update (master branch) and try again?

**Comment by yunhanch** [comment]
It works now, great thanks.
