### ISSUE TITLE
Submitting -ld flag as a job does not run

### ISSUE THREAD

**Issue by Mary-mufford** [precimed/mixer#28]
Hi there

I am trying to run mixer on TSD.

When I run it directly in my working directory it works perfectly. However, when I submit it as a job it fails. It seems to not acknowledge the 'ld' argument that I have given mixer.py. See attached files showing my script, the error log and the output when I run it in my terminal:
<img width="1440" alt="error_log" src="https://user-images.githubusercontent.com/66270009/83507706-330b9400-a4c9-11ea-8a75-5fa049901643.png">
<img width="1440" alt="script" src="https://user-images.githubusercontent.com/66270009/83507725-3a32a200-a4c9-11ea-854f-5e9ab26ca102.png">
<img width="1440" alt="run_in_WD" src="https://user-images.githubusercontent.com/66270009/83507773-4dde0880-a4c9-11ea-948f-9d7267c41887.png">

**Comment by ofrei** [comment]
I think slurm doesn't like that our script is split into multiple lines
with a backslash. Put the entire mixer.py command in one line.
