### ISSUE TITLE
fitting the model gives error: differential_evolution() got an unexpected keyword argument 'updating'

### ISSUE THREAD

**Issue by Mary-mufford** [precimed/mixer#29]
Hi there,

I am using TSD and when I try fit the model to my data I get the following error: differential_evolution() got an unexpected keyword argument 'updating' and the .json files are not generated. Any help with this would be greatly appreciated. See below screenshots of my script, log files, and outputs
<img width="1440" alt="log" src="https://user-images.githubusercontent.com/66270009/83508269-f5f3d180-a4c9-11ea-8923-f88515664ff5.png">
<img width="1440" alt="outputs" src="https://user-images.githubusercontent.com/66270009/83508275-f9875880-a4c9-11ea-9127-e1a40b3d86a1.png">

:
<img width="1440" alt="script (1)" src="https://user-images.githubusercontent.com/66270009/83508179-dbb9f380-a4c9-11ea-8241-b2b7d78fe938.png">

**Comment by ofrei** [comment]
Hi,
You need to update your scipy to at least 1.2.1. This is available on TSD
(solved at rt.uio.no #3652853  )
Kind regards
Alex
