### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by WQ-CHENG** [precimed/mixer#35]
Hi
I've updated MiXeR from v1.2 to v1.3 on SAGA. Now I wanna have a short-time testrun before the MiXeR analysis. So I set the `SBATCH --array=1` ;  `SBATCH --time=1:00:00` ; `SBATCH --cpus-per-task=20`. It reported RuntimeError (see details below). 
I wonder is it because 1:00:00 is too short and I have to set `SBATCH --time=1-00:00:00` ? 

     30 INFO:root:__init__(lib_name=/cluster/home/wqcheng/workspace/Applications/mixer/src/build/lib/libbgmg.so, context_id=0)
     31 Traceback (most recent call last):
     32   File "/cluster/home/wqcheng/workspace/Applications/mixer/precimed/mixer.py", line 23, in <module>
     33     args.func(args)
     34   File "/cluster/projects/nn9114k/weiqiuc/Applications/mixer/precimed/mixer/cli.py", line 710, in execute_fit2_or_test2_parser
     35     results = init_results_struct(libbgmg, args)
     36   File "/cluster/projects/nn9114k/weiqiuc/Applications/mixer/precimed/mixer/cli.py", line 639, in init_results_struct
     37     results['options']['sum_weights'] = float(np.sum(libbgmg.weights))
     38   File "/cluster/projects/nn9114k/weiqiuc/Applications/mixer/precimed/mixer/libbgmg.py", line 168, in weights
     39     return self._get_vec_impl(self.cdll.bgmg_retrieve_weights, np.float32, self.num_tag, trait=None)
     40   File "/cluster/projects/nn9114k/weiqiuc/Applications/mixer/precimed/mixer/libbgmg.py", line 410, in _get_vec_impl
     41     self._check_error(func(*args))
     42   File "/cluster/projects/nn9114k/weiqiuc/Applications/mixer/precimed/mixer/libbgmg.py", line 418, in _check_error
     43     raise RuntimeError(self.get_last_error())
     44 RuntimeError: runtime_error:  arg <= 0

**Comment by ofrei** [comment]
@WQ-CHENG Please point me to the <out>.log file produced by mixer

**Comment by WQ-CHENG** [comment]
> @WQ-CHENG Please point me to the `<out>.log ` file produced by mixer.

Files are located at `cd /cluster/projects/nn9114k/weiqiuc/mixer/Bivdir/PGC_BIP_2019_wave3_vs_UKB42k_SA_160320`
sbatch script:  `less test.sh `
log file:  `less PGC_BIP_2019_wave3_vs_UKB42k_SA_160320.fit.rep1.log`

BTW, the mixer I used here was updated to the latest version, but the log reports it as "Version 1.2.0".

**Comment by ofrei** [comment]
@WQ-CHENG There appears to be a typo in ``--extract /cluster/home/wqcheng/workspace/Ref/sumstats/LDSR/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep.snps``. Then:
```
20201019 10:04:27.218321         constrain analysis to 0 tag variants (due to extract='/cluster/home/wqcheng/workspace/Ref/sumstats/LDSR/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep.snps')
20201019 10:04:27.233181         set_tag_indices(num_snp=9997231, num_tag=0);
```

**Comment by WQ-CHENG** [comment]
> @WQ-CHENG There appears to be a typo in `--extract /cluster/home/wqcheng/workspace/Ref/sumstats/LDSR/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep.snps`. Then:
> 
> ```
> 20201019 10:04:27.218321         constrain analysis to 0 tag variants (due to extract='/cluster/home/wqcheng/workspace/Ref/sumstats/LDSR/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep.snps')
> 20201019 10:04:27.233181         set_tag_indices(num_snp=9997231, num_tag=0);
> ```

Now it works! Thanks for your help and patience!

**Comment by ofrei** [comment]
@WQ-CHENG No worries, I can improve the error message. Good it worked!
