### ISSUE TITLE
Data download problem

### ISSUE THREAD

**Issue by zillurbmb51** [precimed/mixer#38]
Hi there,
I was trying to download Schizophrenia GWAS by Ripke at al. (2014) (search for Download 49 EUR samples here) but failed. No error message appeared but size of the file shown 0.00 Kb and no data downloaded (attached screenshots). Am I trying the right way? Any suggestion? Also there is no problem downloading other data files (GWAS by Lee et al. (2018), broad institute data).
Best regards
Zillur
![data_window1](https://user-images.githubusercontent.com/12833907/104822480-1c8d2f80-5843-11eb-9c07-0a1a7726bd55.png)
![data_window2](https://user-images.githubusercontent.com/12833907/104822481-1d25c600-5843-11eb-82d6-15f2e9e44bad.png)
![data_window3](https://user-images.githubusercontent.com/12833907/104822483-1dbe5c80-5843-11eb-964d-0f77695f9135.png)

**Comment by ofrei** [comment]
@zillurbmb51 Hm, strange. I'm sure there is a way to download this old dataset from PGC website, but I don't have time to investigate what has changed from the time when I wrote the readme file. 
I suggest to take a look here: https://ctg.cncr.nl/software/summary_statistics . This page provides many summary statistics shared by CTG consortia. You could replace PGC SCZ summary statistics with Intelligence Wave2 data., or Insomnia Wave2 data. I will try to updated instructions later. Good thing about CTG is that you can download with ``wget``.  Please give it a try, and just ask here questions if it's not clear how to pre-process CTG data for MiXeR analysis.
Eventually I will try to update instructions to use CTG data, but not in the next weeks.

**Comment by zillurbmb51** [comment]
@ofrei Thank you. I have downloaded the Insomnia data, processed them using sumstats.py and now running ```
python3 <MIXER_ROOT>/precimed/mixer.py ld \
   --lib <MIXER_ROOT>/src/build/lib/libbgmg.so \ ......
```
for each chromosome of reference panel. It is generating 1000G.QC.chr.run4.ld . One thing is that, it is taking too much time, for chromosome 1 and 2. As the rest of the chromosome are finished, I assumed the size of the chromosome matters here, right?

**Comment by ofrei** [comment]
Yes, this is chr-dependent. "ld" step is very time consuming. You could
download pre-generated "ld" files from onedrive. "ld" files only depend on
the reference (1KG), thus there is no need to re-generate them.

**Comment by zillurbmb51** [comment]
@ofrei Thank you. In the next step:  `python3 ../precimed/mixer.py snps --lib ../src/build/lib/libbgmg.so --bim-file ../1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim --out ../1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf05_rand2M_r2p8.rep333 --maf 0.05 --subset 2000000 --r2 0.8`
getting this error:
```
Call: 
./mixer.py snps \
	--out ../1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf05_rand2M_r2p8.rep333 \
	--lib ../src/build/lib/libbgmg.so \
	--bim-file ../1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim 
)
INFO:root:__init__(lib_name=../src/build/lib/libbgmg.so, context_id=0)
Traceback (most recent call last):
  File "../precimed/mixer.py", line 23, in <module>
    args.func(args)
  File "/home/ubuntu/mixer/precimed/mixer/cli.py", line 602, in execute_snps_parser
    libbgmg = initialize_mixer_plugin(args)
  File "/home/ubuntu/mixer/precimed/mixer/cli.py", line 562, in initialize_mixer_plugin
    libbgmg.set_ld_r2_coo_from_file(chr_label, args.ld_file.replace('@', str(chr_label)))
AttributeError: 'NoneType' object has no attribute 'replace'

```
[1000G.EUR.QC.prune_maf05_rand2M_r2p8.rep333.log](https://github.com/precimed/mixer/files/5843330/1000G.EUR.QC.prune_maf05_rand2M_r2p8.rep333.log)
