### ISSUE TITLE
Assertion Error in Fit2 for only 9th CHR: assert np.less_equal(np.sum(self._pi), 1.0) 

### ISSUE THREAD

**Issue by jabbarlinks** [precimed/mixer#39]
Dear Dr. Frei,

I have successfully run codes for univariate and bivariate for real GWAS data. However, when i used simulated GWAS, it works well for univariate. So, there is no error, all outputs are ok until univariate fit1 and test1.

But, for bivariate analysis fit2, it creates all .json file for 1 to 22 chromosomes except the 9th chromosomes. It does not create  .json file for 9th CHR only.

The error message like :assert np.less_equal(np.sum(self._pi), 1.0) AssertionError

However, I have attached the full error message below for your convenience. 

I tried alot to manage it but not yet; but one thing I noticed is that the sum of Pi traitA and TraitB for CHR 9 is greater than 1 like (pi traitA 0.7415 and pi traitB 0.9998), whereas the sum of pi for all other CHR is less than 1.

If you can make an overview and guide about it.   

Many thanks ! 

Call:
./mixer.py fit2 \
        --out /home/TraitA_vs_TraitB/TraitA_vs_TraitB_noMHC.fit.rep.9 \
        --lib /home/mixer/src/build/lib/libbgmg.so \
        --bim-file /home/dir2/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
        --ld-file /home/dir2/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
        --trait1-file /home/TraitA/Test1_TraitA_qc_noMHC.csv.gz \
        --trait2-file /home/TraitB/Test1_TraitB_qc_noMHC.csv.gz \
        --extract /home/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep.9.snps \
        --threads 8 \
        --trait1-params-file /home/TraitA/Test1_TraitA_qc_noMHC.fit.rep.9.json \
        --trait2-params-file /home/TraitB/Test1_TraitB_qc_noMHC.fit.rep.9.json
)
INFO:root:__init__(lib_name=/home/mixer/src/build/lib/libbgmg.so, context_id=0)
INFO:root:log_message(--fit-sequence: ['diffevo-fast', 'neldermead-fast', 'brute1', 'brent1']...)
INFO:root:log_message(Loading univariate constrains for bivariate analysis...)
INFO:root:log_message(trait1: UnivariateParams(_pi: 0.7415289715132274, _sig2_beta: 3.3796678969095297e-08, _sig2_zero: 0.9820527264969727))
INFO:root:log_message(trait2: UnivariateParams(_pi: 0.9998838357192756, _sig2_beta: 9.690443814626e-10, _sig2_zero: 0.9939861260870904))
INFO:root:log_message(fit_type==diffevo-fast...)
Traceback (most recent call last):
  File "/home/mixer/precimed/mixer.py", line 23, in <module>
    args.func(args)
  File "/home/mixer/precimed/mixer/cli.py", line 716, in execute_fit2_or_test2_parser
    params, _, _, optimize_result = apply_bivariate_fit_sequence(args, libbgmg)
  File "/home/mixer/precimed/mixer/cli.py", line 404, in apply_bivariate_fit_sequence
    bounds_left = parametrization.params_to_vec(BivariateParams(params1=params1, params2=params2, pi12=0.05 * max_pi12, rho_beta=-0.95, rho_zero=-0.95))
  File "/home/mixer/precimed/mixer/utils.py", line 348, in __init__
    self._validate()
  File "/home/mixer/precimed/mixer/utils.py", line 369, in _validate
    assert np.less_equal(np.sum(self._pi), 1.0)
AssertionError
(END)

**Comment by ofrei** [comment]
@jabbarlinks I feel for traits with pi=0.74 and pi=0.999 there is no point in running cross-trait MiXeR analysis, poligenicities are so high that the concept of polygenic overlap became meaningless. More formally, when univariate AIC criteria doesn't show significant difference between "mixture model" (pi<1) and "infinitesimal" model my suggestion would be not to run cross-trait MiXeR analysis. If you encounter this for real data, I guess it may indicate too low statistical power (i.e. too small sample size in GWAS). For simulated data I suggest using scenarios with lower fraction of causal variants (i.e. pi=0.001, i.e.  one out of 1000).

**Comment by jabbarlinks** [comment]
Respected Dr. Frei,

Many thanks for your kind comments, definitely it helps me alot in understanding. Once again thankful to you !
