### ISSUE TITLE
getting error to run mixer; TypeError: differential_evolution 

### ISSUE THREAD

**Issue by zillurbmb51** [precimed/mixer#44]
Hi, I was trying to run mixer in tsd (p33) and getting error. `TypeError: differential_evolution() got an unexpected keyword argument 'updating'`
Attached is the full log. Any help?
[slurm-6162160_1.txt](https://github.com/precimed/mixer/files/6312614/slurm-6162160_1.txt)

**Comment by interCM** [comment]
It looks like you have old scipy version ("updated" argument is available only with version >= 1.2.0). Check your scipy version, e.g. with:
`python -c "import scipy; print(scipy.__version__)"`
if your version is older than 1.2.0, then updating scipy should fix the error.

If you are using pip to manage your packages (that's probably the case if you followed README instructions), you can try:
`pip install scipy --upgrade`
if you are using virtual environment, make sure that the environment that you use to run mixer is activated (`source /path/to/your/environment/activate`).

If you run mixer using anaconda, then update with:
`conda update scipy`

**Comment by zillurbmb51** [comment]
Thanks. Updating scipy resolved the issue.
