### ISSUE TITLE
Error when running ./mixer.py fit1

### ISSUE THREAD

**Issue by FernandaSantos13** [precimed/mixer#46]
Hi Alex,

I am trying to run MiXer 1.3 again for my data and I am getting some errors:

#######  Code
module purge   # clear any inherited modules
module load devel/CMake/3.15.3-GCCcore-8.3.0 
module load devel/Boost/1.74.0-GCC-10.2.0 
module load lang/Python/3.7.4-Anaconda3-2021.03
####Univariate model 

python3 $SCRATCH/fsantos/mixer_v1-3_20210429/mixer/precimed/mixer.py fit1 \
      --trait1-file $INPUT_PATH/PGC_MDD_2018_sumstats_mixer_qc_noMHC.csv.gz \
      --out $OUTPUT_PATH/PGC_MDD_2018_sumstats_mixer_qc_noMHC_vPAPER_May2021.fit.rep${SLURM_ARRAY_TASK_ID} \
      --extract $REF_PATH/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep${SLURM_ARRAY_TASK_ID}.snps \
      --bim-file $REF_PATH/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
      --ld-file $REF_PATH/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
      --lib  $SCRATCH/fsantos/mixer_v1-3_20210429/mixer/src/build/lib/libbgmg.so \

########

######## .out file

> $ cat slurm-37647.out

The following have been reloaded with a version change:
  1) compiler/GCCcore/8.3.0 => compiler/GCCcore/10.2.0
  2) lib/zlib/1.2.11-GCCcore-8.3.0 => lib/zlib/1.2.11-GCCcore-10.2.0
  3) tools/bzip2/1.0.8-GCCcore-8.3.0 => tools/bzip2/1.0.8-GCCcore-10.2.0

INFO:root:__init__(lib_name=/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/src/build/lib/libbgmg.so, context_id=0)
INFO:root:init_log(/genome/scratch/diniz/fsantos/DINIZprojects/AD_vs_BP/mixer_analyses/PGC_MDD_2018_sumstats_mixer_qc_noMHC_vPAPER_May2021.fit.rep.log)
INFO:root:log_message(***********************************************************************
* mixer.py: Univariate and Bivariate Causal Mixture for GWAS
* Version 1.2.0
* (c) 2016-2020 Oleksandr Frei, Alexey A. Shadrin, Dominic Holland
* Norwegian Centre for Mental Disorders Research / University of Oslo
* Center for Multimodal Imaging and Genetics / UCSD
* GNU General Public License v3
***********************************************************************
Call:
./mixer.py fit1 \
        --out /genome/scratch/diniz/fsantos/DINIZprojects/AD_vs_BP/mixer_analyses/PGC_MDD_2018_sumstats_mixer_qc_noMHC_vPAPER_May2021.fit.rep \
        --lib /genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/src/build/lib/libbgmg.so \
        --bim-file /genome/scratch/diniz/fsantos/DINIZprojects/reference_files/mixer1.3_20210430/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
        --ld-file /genome/scratch/diniz/fsantos/DINIZprojects/reference_files/mixer1.3_20210430/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
        --trait1-file /genome/scratch/diniz/fsantos/DINIZprojects/AD_vs_BP/mixer_analyses/PGC_MDD_2018_sumstats_mixer_qc_noMHC.csv.gz \
        --extract /genome/scratch/diniz/fsantos/DINIZprojects/reference_files/mixer1.3_20210430/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep.snps
)
INFO:root:__init__(lib_name=/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/src/build/lib/libbgmg.so, context_id=0)
Traceback (most recent call last):
  File "/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/precimed/mixer.py", line 23, in <module>
    args.func(args)
  File "/external/mgmt3/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/precimed/mixer/cli.py", line 647, in execute_fit1_or_test1_parser
    results = init_results_struct(libbgmg, args)
  File "/external/mgmt3/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/precimed/mixer/cli.py", line 639, in init_results_struct
    results['options']['sum_weights'] = float(np.sum(libbgmg.weights))
  File "/external/mgmt3/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/precimed/mixer/libbgmg.py", line 168, in weights
    return self._get_vec_impl(self.cdll.bgmg_retrieve_weights, np.float32, self.num_tag, trait=None)
  File "/external/mgmt3/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/precimed/mixer/libbgmg.py", line 410, in _get_vec_impl
    self._check_error(func(*args))
  File "/external/mgmt3/genome/scratch/diniz/fsantos/mixer_v1-3_20210429/mixer/precimed/mixer/libbgmg.py", line 418, in _check_error
    raise RuntimeError(self.get_last_error())
RuntimeError: runtime_error:  arg <= 0
`
Could you please help me to find out what is wrong? Thank you so much and best regards.

Fernanda

**Comment by ofrei** [comment]
@FernandaSantos13 there should be an <out>.log file with more info, could you attach it here or send it to my e-mail ?

**Comment by FernandaSantos13** [comment]
@ofrei Yes! For sure!
[PGC_MDD_2018_sumstats_mixer_qc_noMHC_vPAPER_May2021.fit.rep.log](https://github.com/precimed/mixer/files/6518634/PGC_MDD_2018_sumstats_mixer_qc_noMHC_vPAPER_May2021.fit.rep.log)

**Comment by ofrei** [comment]
This part is relevant, it shows that after applying ``--extract`` argument the number of tag SNPs dropped to 0. 
This is most likely because ``--extract`` file does not exist. It ends with ``rep.snps`` while it should be ``rep1.snps``, ``rep2.snps``, etc - dependig on ``SLURM_ARRAY_TASK_ID``.
Do you have ``--array`` in your SLURM job?
Take a look at https://github.com/precimed/mixer#upgrade-nodes-from-mixer-v12-to-v13

```
 constrain analysis to 8003224 tag variants (due to trait1_file='/genome/scratch/diniz/fsantos/DINIZprojects/AD_vs_BP/mixer_analyses/PGC_MDD_2018_sumstats_mixer_qc_noMHC.csv.gz')
20210520 14:05:54.397924	 constrain analysis to 0 tag variants (due to extract='/genome/scratch/diniz/fsantos/DINIZprojects/reference_files/mixer1.3_20210430/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep.snps')
20210520 14:05:54.416866	
```

**Comment by FernandaSantos13** [comment]
@ofrei No... I did not have this tag for fit 1. Thank you. It is running again with the following flags: 

##Job name
#SBATCH --job-name=mixer_MDD_fit1_20May2021
##Job resources

# Wall clock limit:
#SBATCH --time=0-24:00:00
#SBATCH --cpus-per-task=8
# Max memory usage:
#SBATCH --mem-per-cpu=7600M
#SBATCH --array=1-20

I will let you know if it worked.

**Comment by FernandaSantos13** [comment]
It worked!!! Thanks!
