### ISSUE TITLE
Error when running mixer_figures.py - Key error:'point_estimate'

### ISSUE THREAD

**Issue by FernandaSantos13** [precimed/mixer#47]
Hi Alex, 

I am having issues when running mixer_figures.py. You can see the error in the attached file. It says: Key error:'point_estimate'. Would you know what is happening?
![image](https://user-images.githubusercontent.com/7333375/123485029-56731680-d5d7-11eb-9798-6329e8c5b46f.png)

**Comment by ofrei** [comment]
Hi @FernandaSantos13 
Try adding "--statistic mean std" to your command, as in the following example: https://github.com/comorment/containers/blob/main/usecases/mixer_real.md

**Comment by ofrei** [comment]
Yes, this works - please share by email
