### ISSUE TITLE
Runtime error: unexpected header error

### ISSUE THREAD

**Issue by zillurbmb51** [precimed/mixer#54]
Hi,
I was trying to run mixer and getting attached error. Runtime error: invalid argument ....dep.sumstats.gz  unexpected header.

Any help?
[slurm-12146839_10.txt](https://github.com/precimed/mixer/files/7762570/slurm-12146839_10.txt)
![dep_sumstats_head](https://user-images.githubusercontent.com/12833907/147091937-06d1a085-fe5a-4a6c-b1bd-bb8a1f1927ab.png)

**Comment by interCM** [comment]
I think, "required N" column is missing. Can you try to add it (e.g. using "sumstats.py neff") and then rerun mixer? Also take a look at "Data preparation" section in the readme.

**Comment by zillurbmb51** [comment]
Thank you. It resolved the issue.
