### ISSUE TITLE
The link to download .ld and .snp files no longer exists

### ISSUE THREAD

**Issue by yyy-nkl** [precimed/mixer#63]
The link (https://github.com/comorment/containers/tree/main/reference/ldsc/1000G_EUR_Phase3_plink) to download .ld and .snp files no longer exists to download .ld and .snp files no longer exist. It shows 404 error.  I tried to generate it myself but it was very slow, so I want to download the generated file. Could you help provide another link that works?

Thank you in advance for your help!

**Comment by ofrei** [comment]
@yyy-nkl the files are available here https://github.com/comorment/mixer/tree/main/reference/ldsc/1000G_EUR_Phase3_plink
please let me know if some old references were not updated

**Comment by yyy-nkl** [comment]
Thank you for your help!&nbsp;
I have another question.&nbsp;
Why need to generate 20 repeats of file.rep${SLURM_ARRAY_TASK_ID}.snps files? Why is the number of repetitions not some other number?  I found that it takes a long time to fit the model in univariate analysis and it takes 24h or more, so I would like to ask if reducing the number of repeats will have any impact? 
Thank you in advance for your help!
------------------

G.Y.
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Oleksandr ***@***.***&gt;;
Send time:&nbsp;Thursday, Dec 29, 2022 6:22 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [precimed/mixer] The link to download .ld and .snp files no longer exists (Issue #63)





 
@yyy-nkl the files are available here https://github.com/comorment/mixer/tree/main/reference/ldsc/1000G_EUR_Phase3_plink
 please let me know if some old references were not updated

**Comment by ofrei** [comment]
@yyy-nkl the results are averaged across 20 repeats to provide more stable point estimate overall (in case of convergence issues, e.g. if a single run lead to an outlier estimates), and get an estimate of standard deviation of those point estimates. There is nothing special about N=20 repeats, you may consider using e.g. 10 repeats, though I think it's too few for estimating a standard deviation (even 20 is quite low).

**Comment by yyy-nkl** [comment]
Thank you for your patient explanation!


------------------

G.Y.
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Oleksandr ***@***.***&gt;;
Send time:&nbsp;Thursday, Dec 29, 2022 7:46 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [precimed/mixer] The link to download .ld and .snp files no longer exists (Issue #63)





 
@yyy-nkl the results are averaged across 20 repeats to provide more stable point estimate overall (in case of convergence issues, e.g. if a single run lead to an outlier estimates), and get an estimate of standard deviation of those point estimates. There is nothing special about N=20 repeats, you may consider using e.g. 10 repeats, though I think it's too few for estimating a standard deviation (even 20 is quite low).
