### ISSUE TITLE
Download 1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.repNN.snps

### ISSUE THREAD

**Issue by zqsha** [precimed/mixer#65]
Hi there.
I found MiXer has updated from 1.2 to 1.3. In the update log, it mentioned "f you previously downloaded 1kG reference, you need to download 20 new files called 1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.repNN.snps". But, I did not find the link to download these snp lists. Could you please specify the link for downloading the generated snp lists? Thank you so much. I really appreciated it. 
Best,
Cain

**Comment by ofrei** [comment]
Hi, you fill find those files here: https://github.com/comorment/mixer/tree/main/reference/ldsc/1000G_EUR_Phase3_plink sorry about incomplete docs lacking the link!
